/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as SessionsRunSessionIdRouteImport } from './routes/sessions.run.$sessionId'

const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRunSessionIdRoute = SessionsRunSessionIdRouteImport.update({
  id: '/sessions/run/$sessionId',
  path: '/sessions/run/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/questions': typeof QuestionsRoute
  '/sessions/new': typeof SessionsNewRoute
  '/sessions/run/$sessionId': typeof SessionsRunSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questions': typeof QuestionsRoute
  '/sessions/new': typeof SessionsNewRoute
  '/sessions/run/$sessionId': typeof SessionsRunSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/questions': typeof QuestionsRoute
  '/sessions/new': typeof SessionsNewRoute
  '/sessions/run/$sessionId': typeof SessionsRunSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/questions' | '/sessions/new' | '/sessions/run/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/questions' | '/sessions/new' | '/sessions/run/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/questions'
    | '/sessions/new'
    | '/sessions/run/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestionsRoute: typeof QuestionsRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsRunSessionIdRoute: typeof SessionsRunSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/run/$sessionId': {
      id: '/sessions/run/$sessionId'
      path: '/sessions/run/$sessionId'
      fullPath: '/sessions/run/$sessionId'
      preLoaderRoute: typeof SessionsRunSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestionsRoute: QuestionsRoute,
  SessionsNewRoute: SessionsNewRoute,
  SessionsRunSessionIdRoute: SessionsRunSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
